Repository matthewdshepherd/picasso-be, pull requests merged in 2019-12, with the labels that each got.

#1 Install jest testing suite
  package-lock.json
  package.json
Labels: documentation

#3 Set up database data and clean up
  data/catalogs.js
  data/palettes.js
  data/users.js
  db/migrations/20191203140706_initial.js
  knexfile.js
  server.js
Labels: documentation

#4 Seed data into Users, Catalogs and Palettes tables
  data/catalogs.js
  data/palettes.js
  data/users.js
  db/migrations/20191203140706_initial.js
  db/seeds/dev/picasso_seeding.js
  knexfile.js
Labels: enhancement

#5 Add JSON.stringify() to color values in seeding file
  db/migrations/20191203140706_initial.js
  db/seeds/dev/picasso_seeding.js
  knexfile.js
Labels: bug, documentation

#8 Install supertest and other babel dependencies for testing
  .babelrc
  app.js
  app.test.js
  package-lock.json
  package.json
Labels: bug

#10 Mm testing be
  .travis.yml
  app.js
  app.test.js
  package.json
Labels: enhancement

#11 Write server request endpoints and testing
  app.js
  app.test.js
Labels: documentation, testing

#13 Add endpoints and testing
  app.js
  app.test.js
Labels: enhancement, testing

#15 Create GET path for all palettes of a specific user
  app.js
  app.test.js
Labels: enhancement, testing

#16 Update Readme
  README.md
  images/Palette-Picker-Schema.png
Labels: documentation
